Original 0.2.0pre6_plus_fixes_12 tarball

diff --git a/scripts/start_net b/scripts/start_net
--- a/scripts/start_net
+++ b/scripts/start_net
@@ -29,7 +29,7 @@ ALG=open # open == Open System, restricted == Shared Key
 #########################################
 
 
-if [[ $UID != 0 ]]; then echo "You are not root. To insert the module into your kernel, you need to be root. Enter su and try again. Bailing..."; exit 1; fi
+if test "$UID" != "0"; then echo "You are not root. To insert the module into your kernel, you need to be root. Enter su and try again. Bailing..."; exit 1; fi
 
 SYNC=`which sync`
 INSMOD=`which insmod`
@@ -39,12 +39,12 @@ IWPRIV=`which iwpriv`
 ROUTE=`which route`
 SCRIPT_AT=`dirname $0`
 
-if [[ $SYNC == "" ]]; then echo "sync not found. Go get a sane Linux system. Bailing..."; exit 1; fi
-if [[ $INSMOD == "" ]]; then echo "insmod not found. Go get a sane Linux system. Bailing..."; exit 1; fi
-if [[ $IFCONF == "" ]]; then echo "ifconfig not found. I can insert the module for you, but you won't be able to configure your interface."; CONTINUE=ASK; fi
-if [[ $IWCONF == "" ]]; then echo "iwconfig not found. Make sure it is installed. The interface might work without, though."; CONTINUE=ASK; fi
+if test -z "$SYNC"; then echo "sync not found. Go get a sane Linux system. Bailing..."; exit 1; fi
+if test -z "$INSMOD"; then echo "insmod not found. Go get a sane Linux system. Bailing..."; exit 1; fi
+if test -z "$IFCONF"; then echo "ifconfig not found. I can insert the module for you, but you won't be able to configure your interface."; CONTINUE=ASK; fi
+if test -z "$IWCONF"; then echo "iwconfig not found. Make sure it is installed. The interface might work without, though."; CONTINUE=ASK; fi
 
-if [[ $CONTINUE == "ASK" ]]; then echo -n "Problems encountered. Do you want to continue? [n] "; read ANSWER
+if test -z "$CONTINUE"; then echo -n "Problems encountered. Do you want to continue? [n] "; read ANSWER
 case $ANSWER in  ( y | Y | Yes | YES | yes | j | J | ja | Ja | JA ) ;;
                  ( * ) exit 1 ;;
 esac
@@ -52,14 +52,14 @@ fi
 
 MODULE_AT="${SCRIPT_AT}/../src/acx100_pci.o"
 
-if ! [[ -r $MODULE_AT ]]; then echo "Module not found or not readable. Have you built it? This script expects it to be at ../src/acx100_pci.o, relative to the script's location. Bailing..."; exit 1; fi
+if test ! -r "$MODULE_AT"; then echo "Module not found or not readable. Have you built it? This script expects it to be at ../src/acx100_pci.o, relative to the script's location. Bailing..."; exit 1; fi
 
 # FIRMWARE_AT has to be given as an absolute path!!
 FIRMWARE_AT="${SCRIPT_AT}/../firmware"
 
-if ! [[ -r "$FIRMWARE_AT/WLANGEN.BIN" ]]; then echo "Firmware not found or not readable. Have you placed it in the firmware directory or run make extract_firmware once? This script expects it to be at ../firmware/WLANGEN.BIN, relative to the script's location. Bailing..."; exit 1; fi
+if test ! -r "$FIRMWARE_AT/WLANGEN.BIN"; then echo "Firmware not found or not readable. Have you placed it in the firmware directory or run make extract_firmware once? This script expects it to be at ../firmware/WLANGEN.BIN, relative to the script's location. Bailing..."; exit 1; fi
 
-if [[ $RATE != "11M" ]]; then echo "Transfer rate is not 11 Mbps, but $RATE. If something doesn't work, try 11 Mbps."; fi
+if test "$RATE" != "11M"; then echo "Transfer rate is not 11 Mbps, but $RATE. If something doesn't work, try 11 Mbps."; fi
 
 
 # for better debugging
@@ -71,62 +71,62 @@ if [[ $RATE != "11M" ]]; then echo "Transfer rate is not 11 Mbps, but $RATE. If 
 $SYNC
 sleep 1
 
-if [[ `lsmod |grep acx100_pci` ]]; then ${SCRIPT_AT}/stop_net; fi
+if test -n `lsmod |grep acx100_pci`; then ${SCRIPT_AT}/stop_net; fi
 
 $INSMOD $MODULE_AT debug=$DEBUG firmware_dir=$FIRMWARE_AT
-if [[ $? == 0 ]]; then echo "Module successfully inserted."; else echo "Error while inserting module! Bailing..."; exit 1; fi
+if test "$?" = "0"; then echo "Module successfully inserted."; else echo "Error while inserting module! Bailing..."; exit 1; fi
 
-if [[ $IWCONF ]]; then
+if test -n "$IWCONF"; then
 
-if [[ -n "$RATE" ]]; then
+if test -n "$RATE"; then
   echo Setting rate to $RATE.
   $IWCONF $DEV rate $RATE
-  if [[ $? != 0 ]]; then echo Failed.; fi
+  test "$?" != "0" && echo Failed.
 fi
-if [[ -n "$CHAN" ]]; then
+if test -n "$CHAN"; then
   echo Setting channel $CHAN.
   $IWCONF $DEV channel $CHAN
-  if [[ $? != 0 ]]; then echo Failed.; fi
+  test "$?" != "0" && echo Failed.
 fi
-if [[ -n "$TXPOWER" ]]; then
+if test -n "$TXPOWER"; then
   echo Setting Tx power level to $TXPOWER dBm.
   $IWCONF $DEV txpower $TXPOWER
-  if [[ $? != 0 ]]; then echo Failed.; fi
+  test "$?" != "0" && echo Failed.
   sleep 1
 fi
 
 echo Trying to join or setup ESSID $ESSID.
 $IWCONF $DEV essid "$ESSID"
-if [[ $? != 0 ]]; then echo Failed.; fi
+test "$?" != "0" && echo Failed.
 
-if [[ -n "$MODE" ]]; then
+if test -n "$MODE"; then
   echo Setting mode to $MODE.
   $IWCONF $DEV mode $MODE
-  if [[ $? != 0 ]]; then echo Failed.; fi
+  test "$?" != "0" && echo Failed.
 fi
 
-if [[ -n "$KEY" ]]; then
+if test -n "$KEY"; then
   echo Setting key to $KEY, algorithm $ALG.
   $IWCONF $DEV key $ALG "$KEY"
-  if [[ $? != 0 ]]; then echo Failed.; fi
+  test "$?" != "0" && echo Failed.
 fi
 
 fi
 
 # for notebook use - a power LED is sooo useless anyway ;-))
-#[[ $IWPRIV ]] && $IWPRIV $DEV set_led_power 0
+#test -n "$IWPRIV" && "$IWPRIV" $DEV set_led_power 0
 
 
 # Hehe, this can be done after iwconfigs now :)
 $IFCONF $DEV $IP netmask $NETMASK
-if [[ $? != 0 ]]; then echo "Error in \"$IFCONF $DEV $IP netmask $NETMASK\". Bailing..."; exit 1; else echo "Interface has been set up successfully."; fi
+if test "$?" != "0"; then echo "Error in \"$IFCONF $DEV $IP netmask $NETMASK\". Bailing..."; exit 1; else echo "Interface has been set up successfully."; fi
 
 # Finally, let's do some tweaking to make sure we don't have any
 # buffer management problems (yeah, it's an ugly workaround!)
 $IFCONF $DEV mtu 576
-if [[ $? != 0 ]]; then echo "Error in \"$IFCONF $DEV mtu 576\". Bailing..."; exit 1; fi
+if test "$?" != "0"; then echo "Error in \"$IFCONF $DEV mtu 576\". Bailing..."; exit 1; fi
 
-if [[ -n "$GATEWAY" ]]; then
+if test -n "$GATEWAY"; then
   $ROUTE add default gw $GATEWAY
 fi
 
